/* Service worker – Phiếu bài tập cho bé. Generated by build.py; do not edit in /workspace/site. */
const VERSION = 'cb180f6a1c';
const PRE = 'pbt-pre-' + VERSION;          // pages + assets + thumbnails (precached)
const RT = 'pbt-rt-cdecc546c0';         // big previews + PDFs (cached on first open)
const PRECACHE = [
"/",
"/404.html",
"/assets/app.js?v=7",
"/assets/app/apple-touch-icon.png",
"/assets/app/favicon-32.png",
"/assets/app/icon-192.png",
"/assets/app/icon-512.png",
"/assets/app/icon-maskable-192.png",
"/assets/app/icon-maskable-512.png",
"/assets/data.js?v=7",
"/assets/icons/animal-buom.svg",
"/assets/icons/animal-ca.svg",
"/assets/icons/animal-cao.svg",
"/assets/icons/animal-chim.svg",
"/assets/icons/animal-ga.svg",
"/assets/icons/animal-heo.svg",
"/assets/icons/animal-huou.svg",
"/assets/icons/animal-khi.svg",
"/assets/icons/animal-meo.svg",
"/assets/icons/animal-rua.svg",
"/assets/icons/animal-sutu.svg",
"/assets/icons/animal-tho.svg",
"/assets/icons/animal-vit.svg",
"/assets/icons/shape4-apple.svg",
"/assets/icons/shape4-balloon.svg",
"/assets/icons/shape4-fish.svg",
"/assets/icons/shape4-flower.svg",
"/assets/icons/shape4-star.svg",
"/assets/icons/shape5-apple.svg",
"/assets/icons/shape5-fish.svg",
"/assets/icons/shape5-flower.svg",
"/assets/icons/shape5-star.svg",
"/assets/ket-qua.js?v=7",
"/assets/lam-bai.js?v=7",
"/assets/meta.js?v=7",
"/assets/pwa.js?v=7",
"/assets/store.js?v=7",
"/assets/style.css?v=7",
"/dem-chu-cai-it-loai/",
"/dem-chu-cai-it-loai/img/dem-chu-cai-it-loai-so-01.webp",
"/dem-chu-cai-it-loai/img/dem-chu-cai-it-loai-so-02.webp",
"/dem-chu-cai-it-loai/img/dem-chu-cai-it-loai-so-03.webp",
"/dem-chu-cai-it-loai/img/dem-chu-cai-it-loai-so-04.webp",
"/dem-chu-cai-it-loai/img/dem-chu-cai-it-loai-so-05.webp",
"/dem-chu-cai-it-loai/img/dem-chu-cai-it-loai-so-06.webp",
"/dem-chu-cai-it-loai/img/dem-chu-cai-it-loai-so-07.webp",
"/dem-chu-cai-it-loai/img/dem-chu-cai-it-loai-so-08.webp",
"/dem-chu-cai-it-loai/img/dem-chu-cai-it-loai-so-09.webp",
"/dem-chu-cai-it-loai/img/dem-chu-cai-it-loai-so-10.webp",
"/dem-chu-cai/",
"/dem-chu-cai/img/dem-chu-cai-so-01.webp",
"/dem-chu-cai/img/dem-chu-cai-so-02.webp",
"/dem-chu-cai/img/dem-chu-cai-so-03.webp",
"/dem-chu-cai/img/dem-chu-cai-so-04.webp",
"/dem-chu-cai/img/dem-chu-cai-so-05.webp",
"/dem-chu-cai/img/dem-chu-cai-so-06.webp",
"/dem-chu-cai/img/dem-chu-cai-so-07.webp",
"/dem-chu-cai/img/dem-chu-cai-so-08.webp",
"/dem-chu-cai/img/dem-chu-cai-so-09.webp",
"/dem-chu-cai/img/dem-chu-cai-so-10.webp",
"/dem-con-vat-it-loai/",
"/dem-con-vat-it-loai/img/dem-con-vat-it-loai-so-01.webp",
"/dem-con-vat-it-loai/img/dem-con-vat-it-loai-so-02.webp",
"/dem-con-vat-it-loai/img/dem-con-vat-it-loai-so-03.webp",
"/dem-con-vat-it-loai/img/dem-con-vat-it-loai-so-04.webp",
"/dem-con-vat-it-loai/img/dem-con-vat-it-loai-so-05.webp",
"/dem-con-vat-it-loai/img/dem-con-vat-it-loai-so-06.webp",
"/dem-con-vat-it-loai/img/dem-con-vat-it-loai-so-07.webp",
"/dem-con-vat-it-loai/img/dem-con-vat-it-loai-so-08.webp",
"/dem-con-vat-it-loai/img/dem-con-vat-it-loai-so-09.webp",
"/dem-con-vat-it-loai/img/dem-con-vat-it-loai-so-10.webp",
"/dem-con-vat/",
"/dem-con-vat/img/dem-con-vat-so-01.webp",
"/dem-con-vat/img/dem-con-vat-so-02.webp",
"/dem-con-vat/img/dem-con-vat-so-03.webp",
"/dem-con-vat/img/dem-con-vat-so-04.webp",
"/dem-con-vat/img/dem-con-vat-so-05.webp",
"/dem-con-vat/img/dem-con-vat-so-06.webp",
"/dem-con-vat/img/dem-con-vat-so-07.webp",
"/dem-con-vat/img/dem-con-vat-so-08.webp",
"/dem-con-vat/img/dem-con-vat-so-09.webp",
"/dem-con-vat/img/dem-con-vat-so-10.webp",
"/ket-qua/",
"/lam-bai/",
"/manifest.webmanifest",
"/toan-be-4-tuoi/",
"/toan-be-4-tuoi/img/toan-be-4-tuoi-so-01.webp",
"/toan-be-4-tuoi/img/toan-be-4-tuoi-so-02.webp",
"/toan-be-4-tuoi/img/toan-be-4-tuoi-so-03.webp",
"/toan-be-5-tuoi/",
"/toan-be-5-tuoi/img/toan-be-5-tuoi-so-01.webp",
"/toan-be-5-tuoi/img/toan-be-5-tuoi-so-02.webp"
];
const OFFLINE_PAGE = '/';

self.addEventListener('install', (e) => {
  e.waitUntil((async () => {
    const c = await caches.open(PRE);
    await c.addAll(PRECACHE.map((u) => new Request(u, { cache: 'reload' })));
    if (!self.registration.active) await self.skipWaiting();   // first install: take over right away
  })());
});

self.addEventListener('activate', (e) => {
  e.waitUntil((async () => {
    for (const k of await caches.keys()) if (k.startsWith('pbt-') && k !== PRE && k !== RT) await caches.delete(k);
    if (self.registration.navigationPreload) { try { await self.registration.navigationPreload.disable(); } catch (_) {} }
    await self.clients.claim();
  })());
});

self.addEventListener('message', (e) => { if (e.data === 'SKIP_WAITING') self.skipWaiting(); });

function pageKey(url) {            // /lam-bai/?bo=..&so=.. -> /lam-bai/ ; /x/index.html -> /x/
  let p = url.pathname.replace(/index\.html$/, '');
  if (!p.endsWith('/') && !/\.[a-z0-9]+$/i.test(p)) p += '/';
  return p;
}
async function fromCache(req, keys) {
  for (const k of keys) { const r = await caches.match(k); if (r) return r; }
  return caches.match(req, { ignoreSearch: true });
}
async function networkFirstPage(req) {
  const url = new URL(req.url), key = pageKey(url);
  try {
    const res = await Promise.race([
      fetch(req),
      new Promise((_, rej) => setTimeout(() => rej(new Error('timeout')), 4000)),
    ]);
    if (res && res.ok && res.type === 'basic' && !res.redirected) { const c = await caches.open(PRE); c.put(key, res.clone()); }
    return res;
  } catch (_) {
    return (await fromCache(req, [key, url.pathname])) || (await caches.match(OFFLINE_PAGE)) ||
      new Response('<h1>Đang ngoại tuyến</h1>', { headers: { 'Content-Type': 'text/html; charset=utf-8' } });
  }
}
async function cacheFirst(req, cacheName) {
  const hit = await caches.match(req);
  if (hit) return hit;
  const res = await fetch(req);
  if (res && res.ok && res.type === 'basic') { const c = await caches.open(cacheName); c.put(req, res.clone()); }
  return res;
}

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;
  if (req.mode === 'navigate') { e.respondWith(networkFirstPage(req)); return; }
  if (/\.(pdf|webp|png|svg)$/i.test(url.pathname)) { e.respondWith(cacheFirst(req, RT)); return; }
  e.respondWith((async () => {
    const hit = await caches.match(req);                   // exact URL incl. ?v= (versioned assets)
    if (hit) return hit;
    try { return await fetch(req); }
    catch (err) { const r = await caches.match(req, { ignoreSearch: true }); if (r) return r; throw err; }
  })());
});
